global_frame: map
robot_base_frame: laser_link_KoBot
update_frequency: 5.0
static_map: true
rolling_window: false
track_unknown_space: true

#inflation_global:
#    inflation_radius: 0.25

plugins:
#  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_global,               type: "costmap_2d::InflationLayer"}
